import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';
import { formatSmartTitle } from '../utils/typography';
import { BrandRepository } from '../storage/brandRepository';

export function generateCyprusDestinationFocusedCanvas(campaign: CampaignInfo): CanvasData {
  const headline = formatSmartTitle(campaign.title);
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;
  const brandKit = BrandRepository.getBrandKit();

  const elements: CanvasLayer[] = [
    {
      id: 'bg-image',
      name: 'Destination Dominant Photo',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: campaign.backgroundImageUrl || 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1080&q=80',
      fit: 'cover',
      locked: true,
      visible: true,
      zIndex: 1,
    },
    {
      id: 'bg-vignette',
      name: 'Editorial Magazine Vignette Overlay',
      type: 'rect',
      x: 0,
      y: 750,
      width: 1080,
      height: 1170,
      fill: 'linear-gradient(180deg, rgba(8,46,99,0) 0%, rgba(8,46,99,0.85) 40%, rgba(4,20,46,0.98) 100%)',
      locked: true,
      visible: true,
      zIndex: 2,
    },
    ...(brandKit.logoUrl
      ? [
          {
            id: 'logo-custom-img',
            name: 'Piertur Custom Logo Image',
            type: 'image' as const,
            x: 60,
            y: 80,
            width: 240,
            height: 64,
            src: brandKit.logoUrl,
            fit: 'contain' as const,
            locked: true,
            visible: true,
            zIndex: 4,
          },
        ]
      : [
          {
            id: 'logo-top-box',
            name: 'Top Logo Pill',
            type: 'rect' as const,
            x: 60,
            y: 80,
            width: 260,
            height: 60,
            fill: 'rgba(8, 46, 99, 0.9)',
            borderRadius: 14,
            stroke: '#FFB21C',
            strokeWidth: 2,
            locked: true,
            visible: true,
            zIndex: 3,
          },
          {
            id: 'logo-top-text',
            name: 'Piertur Logo Text',
            type: 'text' as const,
            x: 82,
            y: 95,
            text: 'PIERTUR',
            fontSize: 28,
            fontWeight: '800',
            fill: '#FFFFFF',
            letterSpacing: 3,
            locked: true,
            visible: true,
            zIndex: 4,
          },
        ]),
    {
      id: 'title-editorial-primary',
      name: 'Editorial Primary Title',
      type: 'text',
      x: 60,
      y: 1020,
      text: headline.primary,
      fontSize: 96,
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 3,
      lineHeight: 1.05,
      locked: true,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'title-editorial-sub',
      name: 'Editorial Subtitle',
      type: 'text',
      x: 60,
      y: 1130,
      text: headline.secondary || 'KEŞİF TURLARI',
      fontSize: 42,
      fontWeight: '800',
      fill: '#FFB21C',
      letterSpacing: 2,
      locked: true,
      visible: true,
      zIndex: 6,
    },
    {
      id: 'price-floating-prefix',
      name: 'Floating Price Prefix',
      type: 'text',
      x: 60,
      y: 1240,
      text: campaign.pricePrefix.toUpperCase(),
      fontSize: 24,
      fontWeight: '800',
      fill: '#FFB21C',
      locked: true,
      visible: true,
      zIndex: 8,
    },
    {
      id: 'price-floating-val',
      name: 'Floating Price Amount',
      type: 'text',
      x: 60,
      y: 1280,
      text: priceFormatted,
      fontSize: 96,
      fontWeight: '900',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 9,
    },
    {
      id: 'cta-btn-bg',
      name: 'CTA Button Frame',
      type: 'rect',
      x: 60,
      y: 1580,
      width: 960,
      height: 110,
      fill: '#E31C24',
      borderRadius: 24,
      locked: true,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'cta-btn-text',
      name: 'CTA Text',
      type: 'text',
      x: 540,
      y: 1614,
      text: `${campaign.ctaText.toUpperCase()} ▸`,
      fontSize: 36,
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 3,
      textAlign: 'center',
      locked: true,
      visible: true,
      zIndex: 11,
    },
    {
      id: 'footer-bar',
      name: 'Footer Website',
      type: 'text',
      x: 60,
      y: 1800,
      text: `🌐 ${brandKit.website || 'piertur.com'}  •  📸 ${brandKit.socialHandle || '@piertur'}  •  📞 ${brandKit.phone || '444 0 743'}`,
      fontSize: 26,
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 12,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
