import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';

export function generateCyprusPremiumCanvas(campaign: CampaignInfo): CanvasData {
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;

  const elements: CanvasLayer[] = [
    {
      id: 'bg-image',
      name: 'Luxury Hotel Photo',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: campaign.backgroundImageUrl || 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1080&q=80',
      fit: 'cover',
      locked: false,
      visible: true,
      zIndex: 1,
    },
    {
      id: 'luxury-frame-top',
      name: 'Luxury Dark Navy Top Panel',
      type: 'rect',
      x: 50,
      y: 50,
      width: 980,
      height: 480,
      fill: '#082E63',
      borderRadius: 32,
      stroke: '#FFB21C',
      strokeWidth: 3,
      opacity: 0.95,
      locked: false,
      visible: true,
      zIndex: 2,
    },
    {
      id: 'gold-badge',
      name: 'Premium Edition Badge',
      type: 'text',
      x: 100,
      y: 90,
      text: '★ PREMIUM SELECTION ★',
      fontSize: 22,
      fontWeight: '700',
      fill: '#FFB21C',
      letterSpacing: 4,
      locked: false,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'title-text',
      name: 'Premium Title',
      type: 'text',
      x: 100,
      y: 140,
      text: campaign.title.toUpperCase(),
      fontSize: 70,
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 4,
    },
    {
      id: 'sub-text',
      name: 'Premium Subtitle',
      type: 'text',
      x: 100,
      y: 230,
      text: campaign.subtitle,
      fontSize: 32,
      fontWeight: '500',
      fill: '#E2E8F0',
      locked: false,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'dur-text',
      name: 'Duration Badge',
      type: 'text',
      x: 100,
      y: 310,
      text: `${campaign.nights} Gece Lüks Konaklama`,
      fontSize: 28,
      fontWeight: '700',
      fill: '#0B63CE',
      locked: false,
      visible: true,
      zIndex: 6,
    },
    {
      id: 'price-card-bottom',
      name: 'Price Bottom Panel',
      type: 'rect',
      x: 50,
      y: 1420,
      width: 980,
      height: 420,
      fill: '#082E63',
      borderRadius: 32,
      stroke: '#FFB21C',
      strokeWidth: 3,
      opacity: 0.95,
      locked: false,
      visible: true,
      zIndex: 7,
    },
    {
      id: 'price-prefix',
      name: 'Price Prefix',
      type: 'text',
      x: 100,
      y: 1460,
      text: campaign.pricePrefix.toUpperCase(),
      fontSize: 24,
      fontWeight: '700',
      fill: '#FFB21C',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 8,
    },
    {
      id: 'price-val',
      name: 'Price Value',
      type: 'text',
      x: 100,
      y: 1500,
      text: priceFormatted,
      fontSize: 100,
      fontWeight: '800',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 9,
    },
    {
      id: 'cta-btn',
      name: 'Gold CTA Button',
      type: 'rect',
      x: 100,
      y: 1680,
      width: 880,
      height: 100,
      fill: '#FFB21C',
      borderRadius: 20,
      locked: false,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'cta-text',
      name: 'Gold CTA Text',
      type: 'text',
      x: 390,
      y: 1712,
      text: campaign.ctaText.toUpperCase(),
      fontSize: 34,
      fontWeight: '800',
      fill: '#082E63',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 11,
    },
  ];

  return {
    backgroundColor: '#04152E',
    elements,
  };
}
