import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';
import { formatSmartTitle } from '../utils/typography';

export function generateCyprusLastminuteCanvas(campaign: CampaignInfo): CanvasData {
  const headline = formatSmartTitle(campaign.title);
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;

  const elements: CanvasLayer[] = [
    {
      id: 'bg-image',
      name: 'Resort Deal Photo',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: campaign.backgroundImageUrl || 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1080&q=80',
      fit: 'cover',
      locked: true,
      visible: true,
      zIndex: 1,
    },
    {
      id: 'alert-header-bg',
      name: 'Red Alert Header Bar',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 160,
      fill: '#E31C24',
      locked: true,
      visible: true,
      zIndex: 2,
    },
    {
      id: 'alert-header-text',
      name: 'Flash Deal Header Text',
      type: 'text',
      x: 540,
      y: 54,
      text: '⚡ SON DAKİKA FIRSATI ⚡',
      fontSize: 44,
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 4,
      textAlign: 'center',
      locked: true,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'title-box-bg',
      name: 'Title Frame Box',
      type: 'rect',
      x: 60,
      y: 200,
      width: 960,
      height: 320,
      fill: '#082E63',
      borderRadius: 28,
      opacity: 0.96,
      stroke: '#FFB21C',
      strokeWidth: 3,
      locked: true,
      visible: true,
      zIndex: 4,
    },
    {
      id: 'title-deal-primary',
      name: 'Primary Title Text',
      type: 'text',
      x: 100,
      y: 235,
      text: headline.primary,
      fontSize: 84,
      fontWeight: '900',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'title-deal-sub',
      name: 'Subtitle Text',
      type: 'text',
      x: 100,
      y: 335,
      text: headline.secondary || 'FIRSAT TURU',
      fontSize: 38,
      fontWeight: '800',
      fill: '#FFB21C',
      locked: true,
      visible: true,
      zIndex: 6,
    },
    {
      id: 'deal-price-card',
      name: 'Huge Deal Price Card Frame',
      type: 'rect',
      x: 60,
      y: 1100,
      width: 960,
      height: 420,
      fill: '#082E63',
      borderRadius: 36,
      stroke: '#E31C24',
      strokeWidth: 5,
      locked: true,
      visible: true,
      zIndex: 7,
    },
    {
      id: 'price-prefix',
      name: 'Price Prefix Text',
      type: 'text',
      x: 110,
      y: 1140,
      text: campaign.pricePrefix.toUpperCase(),
      fontSize: 26,
      fontWeight: '700',
      fill: '#FFB21C',
      locked: true,
      visible: true,
      zIndex: 8,
    },
    {
      id: 'price-amount',
      name: 'Price Value Text',
      type: 'text',
      x: 110,
      y: 1180,
      text: priceFormatted,
      fontSize: 116,
      fontWeight: '900',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 9,
    },
    {
      id: 'price-suffix',
      name: 'Price Suffix Text',
      type: 'text',
      x: 110,
      y: 1330,
      text: "🚨 Sınırlı Kontenjan! 'den başlayan fiyatlarla",
      fontSize: 26,
      fontWeight: '700',
      fill: '#E31C24',
      locked: true,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'cta-red-btn',
      name: 'Red Flash CTA Button',
      type: 'rect',
      x: 60,
      y: 1580,
      width: 960,
      height: 110,
      fill: '#E31C24',
      borderRadius: 24,
      stroke: '#FFFFFF',
      strokeWidth: 2,
      locked: true,
      visible: true,
      zIndex: 11,
    },
    {
      id: 'cta-red-text',
      name: 'CTA Text',
      type: 'text',
      x: 540,
      y: 1614,
      text: campaign.ctaText.toUpperCase(),
      fontSize: 36,
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 3,
      textAlign: 'center',
      locked: true,
      visible: true,
      zIndex: 12,
    },
    {
      id: 'footer-text',
      name: 'Footer Text',
      type: 'text',
      x: 60,
      y: 1800,
      text: '🌐 piertur.com  •  📸 @piertur  •  📞 444 0 743',
      fontSize: 26,
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 13,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
