import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';

export function generateCyprusLastminuteCanvas(campaign: CampaignInfo): CanvasData {
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;

  const elements: CanvasLayer[] = [
    {
      id: 'bg-image',
      name: 'Resort Photo',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: campaign.backgroundImageUrl || 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1080&q=80',
      fit: 'cover',
      locked: false,
      visible: true,
      zIndex: 1,
    },
    {
      id: 'overlay-red',
      name: 'Red Alert Header Bar',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 180,
      fill: '#E31C24',
      locked: false,
      visible: true,
      zIndex: 2,
    },
    {
      id: 'badge-alert',
      name: 'FLASH OFFER BADGE',
      type: 'text',
      x: 70,
      y: 60,
      text: '⚡ SON DAKİKA FIRSATI ⚡',
      fontSize: 44,
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 4,
      locked: false,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'card-dark',
      name: 'Dark Box',
      type: 'rect',
      x: 70,
      y: 220,
      width: 940,
      height: 380,
      fill: '#082E63',
      borderRadius: 28,
      opacity: 0.95,
      locked: false,
      visible: true,
      zIndex: 4,
    },
    {
      id: 'main-title',
      name: 'Title Text',
      type: 'text',
      x: 110,
      y: 260,
      text: campaign.title.toUpperCase(),
      fontSize: 80,
      fontWeight: '800',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'sub-title',
      name: 'Sub Title Text',
      type: 'text',
      x: 110,
      y: 360,
      text: campaign.subtitle,
      fontSize: 34,
      fontWeight: '600',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 6,
    },
    {
      id: 'price-card-red',
      name: 'Price Highlight Card',
      type: 'rect',
      x: 70,
      y: 1150,
      width: 940,
      height: 380,
      fill: '#082E63',
      borderRadius: 32,
      stroke: '#E31C24',
      strokeWidth: 5,
      locked: false,
      visible: true,
      zIndex: 7,
    },
    {
      id: 'price-val',
      name: 'Price Text',
      type: 'text',
      x: 120,
      y: 1200,
      text: priceFormatted,
      fontSize: 110,
      fontWeight: '800',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 8,
    },
    {
      id: 'price-suf',
      name: 'Suffix Text',
      type: 'text',
      x: 120,
      y: 1340,
      text: "Sınırlı Kontenjan! 'den başlayan fiyatlarla",
      fontSize: 26,
      fontWeight: '600',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 9,
    },
    {
      id: 'cta-red',
      name: 'Red CTA Button',
      type: 'rect',
      x: 70,
      y: 1600,
      width: 940,
      height: 110,
      fill: '#E31C24',
      borderRadius: 24,
      locked: false,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'cta-txt',
      name: 'CTA Text',
      type: 'text',
      x: 390,
      y: 1634,
      text: 'REZERVASYON YAP',
      fontSize: 36,
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 11,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
