import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';

export function generateCyprusPriceFocusedCanvas(campaign: CampaignInfo): CanvasData {
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;
  const durationText = `${campaign.nights} Gece ${campaign.days} Gün • Otel Konaklamalı`;
  const citiesText = `${campaign.departureCities.join(', ')} Çıkışlı`;

  const bgUrl =
    campaign.backgroundImageUrl ||
    'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1080&q=80';

  const elements: CanvasLayer[] = [
    // 1. Background Image
    {
      id: 'bg-image',
      name: 'Background Photo',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: bgUrl,
      fit: 'cover',
      locked: false,
      visible: true,
      zIndex: 1,
    },

    // 2. Dark Blue Gradient Overlay
    {
      id: 'bg-overlay',
      name: 'Gradient Overlay',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      fill: 'linear-gradient(180deg, rgba(8, 46, 99, 0.85) 0%, rgba(8, 46, 99, 0.45) 45%, rgba(8, 46, 99, 0.95) 100%)',
      opacity: 0.9,
      locked: true,
      visible: true,
      zIndex: 2,
    },

    // 3. Top Header Card / Logo area
    {
      id: 'header-badge',
      name: 'Piertur Header Badge',
      type: 'rect',
      x: 70,
      y: 80,
      width: 320,
      height: 80,
      fill: '#082E63',
      borderRadius: 16,
      stroke: '#0B63CE',
      strokeWidth: 2,
      locked: false,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'header-logo-text',
      name: 'Piertur Logo Text',
      type: 'text',
      x: 100,
      y: 100,
      text: 'PIERTUR',
      fontSize: 34,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 3,
      locked: false,
      visible: true,
      zIndex: 4,
    },
    {
      id: 'header-logo-sub',
      name: 'Creative AI Badge',
      type: 'text',
      x: 275,
      y: 108,
      text: 'CREATIVE',
      fontSize: 16,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 4,
    },

    // 4. Main Campaign Title
    {
      id: 'campaign-title-main',
      name: 'Main Title',
      type: 'text',
      x: 70,
      y: 220,
      text: campaign.title.toUpperCase(),
      fontSize: 88,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 2,
      lineHeight: 1.1,
      locked: false,
      visible: true,
      zIndex: 5,
    },

    // 5. Subtitle
    {
      id: 'campaign-subtitle',
      name: 'Subtitle',
      type: 'text',
      x: 70,
      y: 330,
      text: campaign.subtitle,
      fontSize: 36,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '600',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 6,
    },

    // 6. Duration Badge Pill
    {
      id: 'duration-pill',
      name: 'Duration Pill Rect',
      type: 'rect',
      x: 70,
      y: 400,
      width: 480,
      height: 64,
      fill: '#0B63CE',
      borderRadius: 32,
      locked: false,
      visible: true,
      zIndex: 7,
    },
    {
      id: 'duration-text',
      name: 'Duration Text',
      type: 'text',
      x: 100,
      y: 416,
      text: durationText,
      fontSize: 24,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 8,
    },

    // 7. Large Price Card (Center Highlight)
    {
      id: 'price-card-bg',
      name: 'Price Card Box',
      type: 'rect',
      x: 70,
      y: 800,
      width: 940,
      height: 420,
      fill: '#082E63',
      borderRadius: 36,
      stroke: '#FFB21C',
      strokeWidth: 4,
      opacity: 0.95,
      locked: false,
      visible: true,
      zIndex: 9,
    },
    {
      id: 'price-prefix-text',
      name: 'Price Prefix',
      type: 'text',
      x: 120,
      y: 840,
      text: campaign.pricePrefix.toUpperCase(),
      fontSize: 28,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'price-amount-text',
      name: 'Price Amount',
      type: 'text',
      x: 120,
      y: 885,
      text: priceFormatted,
      fontSize: 110,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 11,
    },
    {
      id: 'price-suffix-text',
      name: 'Price Suffix',
      type: 'text',
      x: 120,
      y: 1025,
      text: campaign.priceSuffix,
      fontSize: 26,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '500',
      fill: '#CBD5E1',
      locked: false,
      visible: true,
      zIndex: 12,
    },
    {
      id: 'cities-info-text',
      name: 'Departure Cities Text',
      type: 'text',
      x: 120,
      y: 1120,
      text: `📍 ${citiesText}`,
      fontSize: 26,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 13,
    },

    // 8. Campaign Advantages Tags Badges (Grid layout)
    ...campaign.tags.slice(0, 6).map((tag, idx) => {
      const col = idx % 2;
      const row = Math.floor(idx / 2);
      const tagX = 70 + col * 480;
      const tagY = 1260 + row * 80;

      return [
        {
          id: `tag-pill-${idx}`,
          name: `Tag Pill ${idx + 1}`,
          type: 'rect' as const,
          x: tagX,
          y: tagY,
          width: 450,
          height: 64,
          fill: '#0F172A',
          borderRadius: 18,
          stroke: '#334155',
          strokeWidth: 2,
          locked: false,
          visible: true,
          zIndex: 14,
        },
        {
          id: `tag-text-${idx}`,
          name: `Tag Text ${idx + 1}`,
          type: 'text' as const,
          x: tagX + 24,
          y: tagY + 18,
          text: `✓  ${tag}`,
          fontSize: 22,
          fontFamily: 'Montserrat, sans-serif',
          fontWeight: '600',
          fill: '#FFFFFF',
          locked: false,
          visible: true,
          zIndex: 15,
        },
      ];
    }).flat(),

    // 9. CTA Button
    {
      id: 'cta-btn-bg',
      name: 'CTA Button Background',
      type: 'rect',
      x: 70,
      y: 1560,
      width: 940,
      height: 110,
      fill: '#E31C24',
      borderRadius: 24,
      stroke: '#FFFFFF',
      strokeWidth: 2,
      locked: false,
      visible: true,
      zIndex: 20,
    },
    {
      id: 'cta-btn-text',
      name: 'CTA Button Text',
      type: 'text',
      x: 390,
      y: 1594,
      text: campaign.ctaText.toUpperCase(),
      fontSize: 36,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 3,
      textAlign: 'center',
      locked: false,
      visible: true,
      zIndex: 21,
    },

    // 10. Footer Section
    {
      id: 'footer-bg',
      name: 'Footer Background Bar',
      type: 'rect',
      x: 0,
      y: 1770,
      width: 1080,
      height: 150,
      fill: '#041836',
      locked: true,
      visible: true,
      zIndex: 22,
    },
    {
      id: 'footer-website',
      name: 'Footer Website',
      type: 'text',
      x: 70,
      y: 1820,
      text: '🌐 piertur.com',
      fontSize: 28,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 23,
    },
    {
      id: 'footer-instagram',
      name: 'Footer Instagram',
      type: 'text',
      x: 430,
      y: 1820,
      text: '📸 @piertur',
      fontSize: 28,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 23,
    },
    {
      id: 'footer-phone',
      name: 'Footer Phone',
      type: 'text',
      x: 750,
      y: 1820,
      text: '📞 444 0 743',
      fontSize: 28,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 23,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
