import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';

export function generateCyprusMinimalCanvas(campaign: CampaignInfo): CanvasData {
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;

  const elements: CanvasLayer[] = [
    {
      id: 'bg-solid',
      name: 'Solid Dark Background',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      fill: '#082E63',
      locked: true,
      visible: true,
      zIndex: 1,
    },
    {
      id: 'center-photo',
      name: 'Centered Photo Frame',
      type: 'image',
      x: 90,
      y: 280,
      width: 900,
      height: 900,
      src: campaign.backgroundImageUrl || 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1080&q=80',
      fit: 'cover',
      borderRadius: 40,
      locked: false,
      visible: true,
      zIndex: 2,
    },
    {
      id: 'top-logo-txt',
      name: 'Top Logo Text',
      type: 'text',
      x: 90,
      y: 120,
      text: 'PIERTUR',
      fontSize: 40,
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 6,
      locked: false,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'title-txt',
      name: 'Clean Title',
      type: 'text',
      x: 90,
      y: 1240,
      text: campaign.title.toUpperCase(),
      fontSize: 76,
      fontWeight: '800',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 4,
    },
    {
      id: 'sub-txt',
      name: 'Clean Subtitle',
      type: 'text',
      x: 90,
      y: 1330,
      text: campaign.subtitle,
      fontSize: 32,
      fontWeight: '500',
      fill: '#CBD5E1',
      locked: false,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'price-txt',
      name: 'Minimal Price Text',
      type: 'text',
      x: 90,
      y: 1420,
      text: priceFormatted,
      fontSize: 84,
      fontWeight: '800',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 6,
    },
    {
      id: 'cta-rect',
      name: 'Slim CTA Button',
      type: 'rect',
      x: 90,
      y: 1620,
      width: 900,
      height: 100,
      fill: '#0B63CE',
      borderRadius: 20,
      locked: false,
      visible: true,
      zIndex: 7,
    },
    {
      id: 'cta-txt',
      name: 'Slim CTA Text',
      type: 'text',
      x: 390,
      y: 1652,
      text: campaign.ctaText.toUpperCase(),
      fontSize: 32,
      fontWeight: '700',
      fill: '#FFFFFF',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 8,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
