import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';

export function generateCyprusDestinationFocusedCanvas(campaign: CampaignInfo): CanvasData {
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;

  const elements: CanvasLayer[] = [
    {
      id: 'bg-image',
      name: 'Destination Photo',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: campaign.backgroundImageUrl || 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1080&q=80',
      fit: 'cover',
      locked: false,
      visible: true,
      zIndex: 1,
    },
    {
      id: 'bg-overlay',
      name: 'Light Bottom Gradient Overlay',
      type: 'rect',
      x: 0,
      y: 900,
      width: 1080,
      height: 1020,
      fill: 'linear-gradient(180deg, rgba(8,46,99,0) 0%, rgba(8,46,99,0.95) 70%)',
      locked: true,
      visible: true,
      zIndex: 2,
    },
    {
      id: 'logo-top',
      name: 'Logo Pill',
      type: 'rect',
      x: 70,
      y: 90,
      width: 280,
      height: 70,
      fill: '#082E63',
      borderRadius: 20,
      stroke: '#FFB21C',
      strokeWidth: 2,
      locked: false,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'logo-text',
      name: 'Piertur Logo Text',
      type: 'text',
      x: 110,
      y: 110,
      text: 'PIERTUR',
      fontSize: 30,
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 3,
      locked: false,
      visible: true,
      zIndex: 4,
    },
    {
      id: 'destination-title',
      name: 'Large Destination Title',
      type: 'text',
      x: 70,
      y: 1100,
      text: campaign.title.toUpperCase(),
      fontSize: 90,
      fontWeight: '800',
      fill: '#FFFFFF',
      lineHeight: 1.05,
      locked: false,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'destination-sub',
      name: 'Destination Subtitle',
      type: 'text',
      x: 70,
      y: 1210,
      text: campaign.subtitle,
      fontSize: 34,
      fontWeight: '600',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 6,
    },
    {
      id: 'price-badge',
      name: 'Price Floating Badge',
      type: 'rect',
      x: 70,
      y: 1300,
      width: 500,
      height: 140,
      fill: '#0B63CE',
      borderRadius: 28,
      locked: false,
      visible: true,
      zIndex: 7,
    },
    {
      id: 'price-badge-prefix',
      name: 'Price Prefix Text',
      type: 'text',
      x: 100,
      y: 1320,
      text: campaign.pricePrefix.toUpperCase(),
      fontSize: 20,
      fontWeight: '700',
      fill: '#FFB21C',
      locked: false,
      visible: true,
      zIndex: 8,
    },
    {
      id: 'price-badge-val',
      name: 'Price Value Text',
      type: 'text',
      x: 100,
      y: 1350,
      text: priceFormatted,
      fontSize: 60,
      fontWeight: '800',
      fill: '#FFFFFF',
      locked: false,
      visible: true,
      zIndex: 9,
    },
    {
      id: 'cta-btn-bg',
      name: 'CTA Button',
      type: 'rect',
      x: 70,
      y: 1600,
      width: 940,
      height: 110,
      fill: '#E31C24',
      borderRadius: 24,
      locked: false,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'cta-btn-text',
      name: 'CTA Text',
      type: 'text',
      x: 390,
      y: 1634,
      text: campaign.ctaText.toUpperCase(),
      fontSize: 36,
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 2,
      locked: false,
      visible: true,
      zIndex: 11,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
