import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';
import { formatSmartTitle } from '../utils/typography';
import { BrandRepository } from '../storage/brandRepository';

export function generateCyprusPriceFocusedCanvas(campaign: CampaignInfo): CanvasData {
  const headline = formatSmartTitle(campaign.title);
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;
  const hotelText = campaign.hotelName
    ? `${campaign.hotelName.toUpperCase()}`
    : 'BECEREN OTEL';
  const durationBoardText = `${campaign.nights} GECE / ${campaign.days} GÜN • ${
    (campaign.boardType || 'YARIM PANSİYON').toUpperCase()
  }`;
  const citiesText = `📍 ${campaign.departureCities.join(' • ')} ÇIKIŞLI`;
  const badge = (campaign.badgeText || 'SON DAKİKA FIRSATI').toUpperCase();
  const brandKit = BrandRepository.getBrandKit();

  const bgUrl =
    campaign.backgroundImageUrl ||
    'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1080&q=80';

  const elements: CanvasLayer[] = [
    // 1. Single Full-Bleed Destination Photo (0,0 -> 1080,1920 cover, 80%+ Photo Dominance)
    {
      id: 'bg-image',
      name: 'Full-Bleed Single Photo Background',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: bgUrl,
      fit: 'cover',
      locked: true,
      visible: true,
      zIndex: 1,
    },

    // 2. Minimal Translucent Text Fades (NO HORIZONTAL SLICING, NO SOLID NAVY BLOCKS)
    {
      id: 'bg-overlay-top',
      name: 'Top Text Readability Fade',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 480,
      fill: 'linear-gradient(180deg, rgba(4, 20, 48, 0.65) 0%, rgba(4, 20, 48, 0.2) 60%, rgba(4, 20, 48, 0) 100%)',
      opacity: 0.85,
      locked: true,
      visible: true,
      zIndex: 2,
    },
    {
      id: 'bg-overlay-bottom',
      name: 'Bottom Price Readability Fade',
      type: 'rect',
      x: 0,
      y: 1000,
      width: 1080,
      height: 920,
      fill: 'linear-gradient(180deg, rgba(4, 20, 48, 0) 0%, rgba(4, 20, 48, 0.55) 35%, rgba(4, 20, 48, 0.92) 100%)',
      opacity: 0.92,
      locked: true,
      visible: true,
      zIndex: 2,
    },

    // 3. Top Left: Piertur Logo Mark
    ...(brandKit.logoUrl
      ? [
          {
            id: 'logo-custom-img',
            name: 'Piertur Custom Logo Image',
            type: 'image' as const,
            x: 60,
            y: 70,
            width: 240,
            height: 60,
            src: brandKit.logoUrl,
            fit: 'contain' as const,
            locked: true,
            visible: true,
            zIndex: 4,
          },
        ]
      : [
          {
            id: 'logo-badge-bg',
            name: 'Logo Mark Frame',
            type: 'rect' as const,
            x: 60,
            y: 70,
            width: 250,
            height: 56,
            fill: 'rgba(8, 46, 99, 0.85)',
            borderRadius: 12,
            stroke: '#FFB21C',
            strokeWidth: 2,
            locked: true,
            visible: true,
            zIndex: 3,
          },
          {
            id: 'logo-text-primary',
            name: 'Piertur Brand Text',
            type: 'text' as const,
            x: 80,
            y: 84,
            text: 'PIERTUR',
            fontSize: 26,
            fontFamily: 'Montserrat, sans-serif',
            fontWeight: '900',
            fill: '#FFFFFF',
            letterSpacing: 4,
            locked: true,
            visible: true,
            zIndex: 4,
          },
        ]),

    // 4. Top Right: Angled Red Campaign Ribbon
    {
      id: 'campaign-ribbon-bg',
      name: 'Angled Campaign Ribbon',
      type: 'rect',
      x: 600,
      y: 70,
      width: 420,
      height: 60,
      fill: '#E31C24',
      borderRadius: 14,
      stroke: '#FFB21C',
      strokeWidth: 2,
      locked: true,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'campaign-ribbon-text',
      name: 'Campaign Ribbon Text',
      type: 'text',
      x: 810,
      y: 88,
      text: `🔥 ${badge}`,
      fontSize: 20,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 2,
      textAlign: 'center',
      locked: true,
      visible: true,
      zIndex: 4,
    },

    // 5. Hero Editorial Headline: ULUDAĞ + KONAKLAMALI TUR
    {
      id: 'title-primary',
      name: 'Main Destination Headline',
      type: 'text',
      x: 60,
      y: 175,
      text: headline.primary,
      fontSize: 110,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 4,
      lineHeight: 1.0,
      locked: true,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'title-secondary',
      name: 'Secondary Accent Subtitle',
      type: 'text',
      x: 60,
      y: 295,
      text: headline.secondary || 'KONAKLAMALI TUR',
      fontSize: 44,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFB21C',
      letterSpacing: 3,
      locked: true,
      visible: true,
      zIndex: 6,
    },

    // 6. Typographic Hotel Line (NO SOLID BOX OR BAR)
    {
      id: 'hotel-info-text',
      name: 'Hotel Information Text',
      type: 'text',
      x: 60,
      y: 355,
      text: `🏨 ${hotelText} KONAKLAMALI ★★★★★`,
      fontSize: 24,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      letterSpacing: 1,
      locked: true,
      visible: true,
      zIndex: 7,
    },

    // 7. Hero Price Callout (Floating Directly Over Photo Background - NO SOLID CARD BOX!)
    {
      id: 'price-prefix',
      name: 'Hero Price Prefix Callout',
      type: 'text',
      x: 60,
      y: 1120,
      text: campaign.pricePrefix.toUpperCase(),
      fontSize: 26,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFB21C',
      letterSpacing: 3,
      locked: true,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'price-amount',
      name: 'Hero Price Giant Typography',
      type: 'text',
      x: 60,
      y: 1160,
      text: priceFormatted,
      fontSize: 120,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 1,
      locked: true,
      visible: true,
      zIndex: 11,
    },
    {
      id: 'price-suffix',
      name: 'Hero Price Suffix Note',
      type: 'text',
      x: 60,
      y: 1300,
      text: `${campaign.priceSuffix} • ⚡ SINIRLI KONTENJAN`,
      fontSize: 22,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#E2E8F0',
      locked: true,
      visible: true,
      zIndex: 12,
    },

    // 8. Typographic Accommodation & Board Line (NO SOLID DARK BAR)
    {
      id: 'duration-text',
      name: 'Duration Stay Text',
      type: 'text',
      x: 60,
      y: 1350,
      text: `🗓️ ${durationBoardText}`,
      fontSize: 24,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      letterSpacing: 1,
      locked: true,
      visible: true,
      zIndex: 14,
    },

    // 9. Departure Cities Line (NO BLUE BOX)
    {
      id: 'cities-text',
      name: 'Departure Cities Text',
      type: 'text',
      x: 60,
      y: 1400,
      text: citiesText,
      fontSize: 22,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      letterSpacing: 1,
      locked: true,
      visible: true,
      zIndex: 15,
    },

    // 10. Integrated Angled Red Banner CTA (Advertising Banner)
    {
      id: 'cta-button-bg',
      name: 'Angled Red Banner CTA Frame',
      type: 'rect',
      x: 60,
      y: 1560,
      width: 960,
      height: 104,
      fill: '#E31C24',
      borderRadius: 18,
      stroke: '#FFFFFF',
      strokeWidth: 2.5,
      locked: true,
      visible: true,
      zIndex: 20,
    },
    {
      id: 'cta-button-text',
      name: 'CTA Banner Text',
      type: 'text',
      x: 540,
      y: 1593,
      text: `${campaign.ctaText.toUpperCase()} ▸`,
      fontSize: 34,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 3,
      textAlign: 'center',
      locked: true,
      visible: true,
      zIndex: 21,
    },

    // 11. Minimal Thin Branded Corporate Footer Strip
    {
      id: 'footer-bar-bg',
      name: 'Corporate Footer Bar Container',
      type: 'rect',
      x: 0,
      y: 1815,
      width: 1080,
      height: 105,
      fill: 'rgba(4, 20, 48, 0.95)',
      locked: true,
      visible: true,
      zIndex: 22,
    },
    {
      id: 'footer-web',
      name: 'Footer Website Link',
      type: 'text',
      x: 60,
      y: 1852,
      text: `🌐 ${brandKit.website || 'piertur.com'}`,
      fontSize: 24,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 23,
    },
    {
      id: 'footer-social',
      name: 'Footer Social Media Handle',
      type: 'text',
      x: 430,
      y: 1852,
      text: `📸 ${brandKit.socialHandle || '@piertur'}`,
      fontSize: 24,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      locked: true,
      visible: true,
      zIndex: 23,
    },
    {
      id: 'footer-phone',
      name: 'Footer Direct Call Center',
      type: 'text',
      x: 750,
      y: 1852,
      text: `📞 ${brandKit.phone || '444 0 743'}`,
      fontSize: 24,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 23,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
