import { CampaignInfo, CanvasData, CanvasLayer } from '@/types';
import { formatPrice, formatCurrencySymbol } from '../utils/formatters';
import { formatSmartTitle } from '../utils/typography';
import { BrandRepository } from '../storage/brandRepository';

export function generateCyprusPriceFocusedCanvas(campaign: CampaignInfo): CanvasData {
  const headline = formatSmartTitle(campaign.title);
  const priceFormatted = `${formatPrice(campaign.price)} ${formatCurrencySymbol(campaign.currency)}`;
  const hotelText = campaign.hotelName
    ? `${campaign.hotelName.toUpperCase()}`
    : 'BECEREN OTEL';
  const durationBoardText = `${campaign.nights} GECE / ${campaign.days} GÜN • ${
    (campaign.boardType || 'YARIM PANSİYON').toUpperCase()
  }`;
  const citiesText = `📍 ${campaign.departureCities.join(' • ')} ÇIKIŞLI`;
  const badge = (campaign.badgeText || 'SON DAKİKA FIRSATI').toUpperCase();
  const brandKit = BrandRepository.getBrandKit();

  const bgUrl =
    campaign.backgroundImageUrl ||
    'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1080&q=80';

  const elements: CanvasLayer[] = [
    // 1. Full-Bleed Background Destination Photo (65-70%+ Dominance)
    {
      id: 'bg-image',
      name: 'Full-Bleed Destination Photo',
      type: 'image',
      x: 0,
      y: 0,
      width: 1080,
      height: 1920,
      src: bgUrl,
      fit: 'cover',
      locked: true,
      visible: true,
      zIndex: 1,
    },

    // 2. Atmospheric Gradient Vignettes (No Solid Rectangular Boxes)
    {
      id: 'bg-overlay-top',
      name: 'Top Readability Vignette',
      type: 'rect',
      x: 0,
      y: 0,
      width: 1080,
      height: 650,
      fill: 'linear-gradient(180deg, rgba(8, 46, 99, 0.88) 0%, rgba(8, 46, 99, 0.4) 65%, rgba(8, 46, 99, 0) 100%)',
      opacity: 0.9,
      locked: true,
      visible: true,
      zIndex: 2,
    },
    {
      id: 'bg-overlay-bottom',
      name: 'Bottom Content Vignette',
      type: 'rect',
      x: 0,
      y: 900,
      width: 1080,
      height: 1020,
      fill: 'linear-gradient(180deg, rgba(8, 46, 99, 0) 0%, rgba(8, 46, 99, 0.75) 25%, rgba(4, 20, 48, 0.96) 100%)',
      opacity: 0.96,
      locked: true,
      visible: true,
      zIndex: 2,
    },

    // 3. Top Left: Piertur Logo Mark (Uses Custom Transparent Logo if loaded)
    ...(brandKit.logoUrl
      ? [
          {
            id: 'logo-custom-img',
            name: 'Piertur Custom Logo Image',
            type: 'image' as const,
            x: 60,
            y: 75,
            width: 240,
            height: 64,
            src: brandKit.logoUrl,
            fit: 'contain' as const,
            locked: true,
            visible: true,
            zIndex: 4,
          },
        ]
      : [
          {
            id: 'logo-badge-bg',
            name: 'Logo Mark Frame',
            type: 'rect' as const,
            x: 60,
            y: 75,
            width: 260,
            height: 64,
            fill: 'rgba(8, 46, 99, 0.9)',
            borderRadius: 14,
            stroke: '#FFB21C',
            strokeWidth: 2,
            locked: true,
            visible: true,
            zIndex: 3,
          },
          {
            id: 'logo-text-primary',
            name: 'Piertur Brand Text',
            type: 'text' as const,
            x: 82,
            y: 92,
            text: 'PIERTUR',
            fontSize: 28,
            fontFamily: 'Montserrat, sans-serif',
            fontWeight: '900',
            fill: '#FFFFFF',
            letterSpacing: 4,
            locked: true,
            visible: true,
            zIndex: 4,
          },
        ]),

    // 4. Top Right: Angled Red Campaign Ribbon
    {
      id: 'campaign-ribbon-bg',
      name: 'Angled Campaign Ribbon',
      type: 'rect',
      x: 580,
      y: 75,
      width: 440,
      height: 68,
      fill: '#E31C24',
      borderRadius: 16,
      stroke: '#FFB21C',
      strokeWidth: 2.5,
      locked: true,
      visible: true,
      zIndex: 3,
    },
    {
      id: 'campaign-ribbon-text',
      name: 'Campaign Ribbon Text',
      type: 'text',
      x: 800,
      y: 96,
      text: `🔥 ${badge}`,
      fontSize: 22,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFFFFF',
      letterSpacing: 2,
      textAlign: 'center',
      locked: true,
      visible: true,
      zIndex: 4,
    },

    // 5. Hero Destination Headline
    {
      id: 'title-primary',
      name: 'Main Destination Headline',
      type: 'text',
      x: 60,
      y: 190,
      text: headline.primary,
      fontSize: 110,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 4,
      lineHeight: 1.0,
      locked: true,
      visible: true,
      zIndex: 5,
    },
    {
      id: 'title-secondary',
      name: 'Secondary Accent Subtitle',
      type: 'text',
      x: 60,
      y: 310,
      text: headline.secondary || 'KONAKLAMALI TUR',
      fontSize: 44,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFB21C',
      letterSpacing: 3,
      locked: true,
      visible: true,
      zIndex: 6,
    },

    // 6. Slim Hotel Band
    {
      id: 'hotel-pill-bg',
      name: 'Hotel Information Pill',
      type: 'rect',
      x: 60,
      y: 375,
      width: 480,
      height: 56,
      fill: 'rgba(11, 99, 206, 0.95)',
      borderRadius: 28,
      stroke: '#FFFFFF',
      strokeWidth: 1.5,
      locked: true,
      visible: true,
      zIndex: 7,
    },
    {
      id: 'hotel-pill-text',
      name: 'Hotel Information Text',
      type: 'text',
      x: 86,
      y: 391,
      text: `🏨 ${hotelText} KONAKLAMALI`,
      fontSize: 20,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 8,
    },

    // 7. Floating Hero Price Callout (No Opaque Cards)
    {
      id: 'price-prefix',
      name: 'Hero Price Prefix Callout',
      type: 'text',
      x: 60,
      y: 1040,
      text: campaign.pricePrefix.toUpperCase(),
      fontSize: 26,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '800',
      fill: '#FFB21C',
      letterSpacing: 3,
      locked: true,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'price-amount',
      name: 'Hero Price Giant Typography',
      type: 'text',
      x: 60,
      y: 1080,
      text: priceFormatted,
      fontSize: 120,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 1,
      locked: true,
      visible: true,
      zIndex: 11,
    },
    {
      id: 'price-suffix',
      name: 'Hero Price Suffix Note',
      type: 'text',
      x: 60,
      y: 1220,
      text: `${campaign.priceSuffix} • ⚡ SINIRLI KONTENJAN`,
      fontSize: 22,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#E2E8F0',
      locked: true,
      visible: true,
      zIndex: 12,
    },

    // 8. Duration Stay Pill
    {
      id: 'duration-pill-bg',
      name: 'Duration Stay Pill',
      type: 'rect',
      x: 60,
      y: 1275,
      width: 960,
      height: 60,
      fill: 'rgba(15, 23, 42, 0.9)',
      borderRadius: 18,
      stroke: 'rgba(255, 178, 28, 0.5)',
      strokeWidth: 1.5,
      locked: true,
      visible: true,
      zIndex: 14,
    },
    {
      id: 'duration-pill-text',
      name: 'Duration Stay Text',
      type: 'text',
      x: 88,
      y: 1293,
      text: `🗓️ ${durationBoardText}`,
      fontSize: 22,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 15,
    },

    // 9. Compact Departure Cities Badging
    {
      id: 'cities-badge-text',
      name: 'Departure Cities Text',
      type: 'text',
      x: 60,
      y: 1355,
      text: citiesText,
      fontSize: 22,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      locked: true,
      visible: true,
      zIndex: 16,
    },

    // 10. Benefit Icon Badges (2-Column Grid)
    ...campaign.tags.slice(0, 4).map((tag, idx) => {
      const col = idx % 2;
      const row = Math.floor(idx / 2);
      const tagX = 60 + col * 490;
      const tagY = 1400 + row * 72;

      return [
        {
          id: `adv-pill-${idx}`,
          name: `Advantage Badge ${idx + 1}`,
          type: 'rect' as const,
          x: tagX,
          y: tagY,
          width: 470,
          height: 58,
          fill: 'rgba(8, 46, 99, 0.85)',
          borderRadius: 16,
          stroke: 'rgba(11, 99, 206, 0.8)',
          strokeWidth: 1.5,
          locked: true,
          visible: true,
          zIndex: 17,
        },
        {
          id: `adv-text-${idx}`,
          name: `Advantage Text ${idx + 1}`,
          type: 'text' as const,
          x: tagX + 22,
          y: tagY + 16,
          text: `✔ ${tag}`,
          fontSize: 20,
          fontFamily: 'Montserrat, sans-serif',
          fontWeight: '600',
          fill: '#FFFFFF',
          locked: true,
          visible: true,
          zIndex: 18,
        },
      ];
    }).flat(),

    // 11. Integrated Angled Red Banner CTA Button
    {
      id: 'cta-button-bg',
      name: 'Angled Red Banner CTA Frame',
      type: 'rect',
      x: 60,
      y: 1575,
      width: 960,
      height: 104,
      fill: '#E31C24',
      borderRadius: 24,
      stroke: '#FFFFFF',
      strokeWidth: 2.5,
      locked: true,
      visible: true,
      zIndex: 20,
    },
    {
      id: 'cta-button-text',
      name: 'CTA Banner Text',
      type: 'text',
      x: 540,
      y: 1608,
      text: `${campaign.ctaText.toUpperCase()} ▸`,
      fontSize: 34,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '900',
      fill: '#FFFFFF',
      letterSpacing: 3,
      textAlign: 'center',
      locked: true,
      visible: true,
      zIndex: 21,
    },

    // 12. Branded Corporate Footer Bar
    {
      id: 'footer-bar-bg',
      name: 'Corporate Footer Bar Container',
      type: 'rect',
      x: 0,
      y: 1760,
      width: 1080,
      height: 160,
      fill: '#04152E',
      locked: true,
      visible: true,
      zIndex: 22,
    },
    {
      id: 'footer-web',
      name: 'Footer Website Link',
      type: 'text',
      x: 60,
      y: 1820,
      text: `🌐 ${brandKit.website || 'piertur.com'}`,
      fontSize: 26,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 23,
    },
    {
      id: 'footer-social',
      name: 'Footer Social Media Handle',
      type: 'text',
      x: 430,
      y: 1820,
      text: `📸 ${brandKit.socialHandle || '@piertur'}`,
      fontSize: 26,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFB21C',
      locked: true,
      visible: true,
      zIndex: 23,
    },
    {
      id: 'footer-phone',
      name: 'Footer Direct Call Center',
      type: 'text',
      x: 750,
      y: 1820,
      text: `📞 ${brandKit.phone || '444 0 743'}`,
      fontSize: 26,
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: '700',
      fill: '#FFFFFF',
      locked: true,
      visible: true,
      zIndex: 23,
    },
  ];

  return {
    backgroundColor: '#082E63',
    elements,
  };
}
